global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: pushgateway
    honor_labels: true
    static_configs:
      - targets: ['pushgateway_host:9091']
        labels:
          pushgateway_instance: edametrics
